patients-management-system-PMS/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PdfController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\PrescriptionController;
use App\Http\Controllers\fontend\FontendController;
use App\Http\Controllers\backend\admin\AdminController;
use App\Http\Controllers\backend\admin\AllAdminController;
use App\Http\Controllers\backend\admin\AllPatientController;
use App\Http\Controllers\backend\user\UserProfileController;
use App\Http\Controllers\backend\admin\AdminProfileController;
use App\Http\Controllers\backend\user\UserDeshboardController;
use App\Http\Controllers\backend\user\DoctorCategoryController;
use App\Http\Controllers\backend\admin\AdminDeshboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('fontend.dashboard');
});

// Route::gat('/',[FontendController::class, 'dashboard']);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';



// Admin Controller
Route::prefix('admin')->name('admin.')->controller(AdminController::class)->group(function () {
    Route::get('/', 'adminLoginForm')->name('login.form');
    Route::post('/login', 'adminLogin')->name('login');
});

Route::middleware("admin")->group(function () {
    // Admin Deshboard Controller
    Route::prefix('admin')->name('admin.')->controller(AdminDeshboardController::class)->group(function () {
        Route::get('/register', 'adminRegstrationForm')->name('register.form');
        Route::post('/register/store', 'adminRegstrationStore')->name('register.store');
        Route::get('/deshboard', 'adminDeshboard')->name('deshboard');
        Route::get('/logout', 'adminLogout')->name('logout');
    });

    // Admin Profile Controller
    Route::prefix('admin')->name('admin.')->controller(AdminProfileController::class)->group(function () {
        Route::get('/profile', 'adminProfile')->name('profile');
        Route::post('/update/{id}', 'adminProfileUpdate')->name('profile.update');
    });


    //  All Admin Controller
    Route::prefix('admin')->name('admin.')->controller(AllAdminController::class)->group(function () {
        Route::get('/all/admins', 'allAdmins')->name('all');
        Route::get('/show/{id}', 'showAdmin')->name('show');
        Route::get('/edit/{id}', 'editAdmin')->name('edit');
        Route::put('/update/{id}', 'updateAdmin')->name('update');
        Route::delete('/delete/{id}', 'adminDelete')->name('destroy');
       
    });


    // All Patients Controller
    Route::prefix('patient')->name('patient.')->controller(AllPatientController::class)->group(function () {
        Route::get('/all', 'allPatients')->name('all');
        Route::get('/show/{id}', 'showPatient')->name('show');
        Route::get('/prescription/{id}', 'prescription')->name('prescription');
    });


    // User Profile Controller
    Route::prefix('user')->name('user.')->controller(UserProfileController::class)->group(function () {
        Route::get('/profile', 'UserProfile')->name('profile');
        Route::get('/profile.update', 'UserProfile')->name('profile.update');
        Route::get('/list', 'Userlist')->name('all.list');
    });
});


Route::middleware('auth')->group(function () {

    // User Deshboard Controller
    Route::prefix('user')->name('user.')->controller(UserDeshboardController::class)->group(function () {
        Route::get('/deshboard', 'UserDeshboard')->name('deshboard');
    });

    // Doctor Specialist Controller
    Route::prefix('doctor')->name('user.')->controller(DoctorCategoryController::class)->group(function () {
        Route::get('/list/{id}', 'doctorList')->name('specific.doctor.list');
        Route::get('/specific/show/{id}', 'doctorSpecific')->name('doctor.specific');
    });
});



//pascription controller

Route::prefix('admin')->name('admin.')->controller(PrescriptionController::class)->middleware('admin')->group(function () {
    Route::get('/prescription/list', 'prescription_list')->name('prescription.list');
    Route::get('/prescription/create/{id}', 'patients_prescription')->name('prescription.create');
    Route::post('/prescription/store', 'store')->name('prescription.store');
    Route::get('/prescription/show/{id}', 'show')->name('prescription.show');
});

// pdf 
    
Route::get('/prescription/Pdf', [PdfController::class, 'prescription_Pdf'])->name('prescription.pdf');
Route::get('/appointment/Pdf', [PdfController::class, 'appointment_Pdf'])->name('appointment.pdf');
    

//appointment controller

Route::prefix('appointment')->name('appointment.')->controller(AppointmentController::class)->group(function () {
    // Route::get('/', 'appointment_list')->name('list');
    Route::get('/', 'index')->name('list');
    Route::get('/create/{id}', 'appointment')->name('create');
    Route::get('/show/{id}', 'appointment_show')->name('show');
    Route::post('/store', 'store')->name('store');
    Route::get('/today', 'today_appointment')->name('today');
});

patients-management-system-PMS/app/Models/DoctorCategory.php
<?php

namespace App\Models;

use App\Models\Admin;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class DoctorCategory extends Model
{
    use HasFactory;
    protected $fillable=[
        'name',
    ];

    public function doctor()
    {
       return $this->hasMany(Admin::class, 'doctor_id','id');
    }
}

patients-management-system-PMS/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'phone',
        'doctor_id',
        'role_id',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    
    public function role()
    {
        return $this->belongsTo(Role::class, 'role_id','id');
    }
}

patients-management-system-PMS/app/Http/Controllers/backend/user/DoctorCategoryController.php
<?php

namespace App\Http\Controllers\backend\user;

use App\Models\Admin;
use Illuminate\Http\Request;
use App\Models\DoctorCategory;
use App\Http\Controllers\Controller;

class DoctorCategoryController extends Controller
{
    public function doctorList($id)
    {
        $specific_doctor_category_list = Admin::where('doctor_category',$id)->get();
        return view('backend.user.doctor_category.specific_doctor_category_list', compact('specific_doctor_category_list'));
    }

    public function doctorSpecific($id)
    {
        $doctor = Admin::where('id',$id)->first();
        dd($doctor);
        return view('backend.user.doctor_category.show', compact('doctor'));
    }
}

patients-management-system-PMS/app/Http/Controllers/backend/user/UserDeshboardController.php
<?php

namespace App\Http\Controllers\backend\user;

use session;
use Illuminate\Http\Request;
use App\Models\DoctorCategory;
use App\Http\Controllers\Controller;
use App\Models\Admin;
use Illuminate\Support\Facades\Auth;

class UserDeshboardController extends Controller
{
    public function UserDeshboard(){
      
        $doctors = Admin::where('role_id','2')
        ->get();
        return view('backend.user.deshboard.user_deshboard',compact('doctors'));
    }
    
}

patients-management-system-PMS/app/Http/Controllers/backend/user/UserProfileController.php
<?php

namespace App\Http\Controllers\backend\user;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserProfileController extends Controller
{



    public function UserProfile(){
     
        return view('backend.user.profile');
     }

     public function Userlist()
     {
        $patients = User::all();
        return view('backend.user.alluserlist',compact('patients'));
     }
}

patients-management-system-PMS/resources/views/backend/user/doctor_category/show.blade.php
<x-backend.layout.master>

    <!-- Sidebar Start -->
    <x-backend.partials.sidebar />
    <!-- Sidebar End -->



    <!-- Content Start -->
    <div class="content">
        <!-- Navbar Start -->
        <x-backend.partials.navbar />
        <!-- Navbar End -->

        <!-- content Start -->

        <div class="container">
            <div class="row mx-4">
                <h3 class="text-center mt-3">Doctor Specialist</h3>
                @foreach ($specific_doctor_category_list as $specific_doctor_category_list)
                    <div class="col col-3">
                        <div class="card" style="width: 15rem; margin:auto;">
                            <img src="..." class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">
                                    {{ ucfirst($specific_doctor_category_list->first_name)}} 
                                    {{ ucfirst($specific_doctor_category_list->last_name)}} 
                                </h5>
                                <b class="card-title">{{ 
                                ucfirst($specific_doctor_category_list->doctorCategory->name)
                                 }} Specialist</b>

                                <p class="card-text">Some quick example text to build on the card title and make up
                                    the
                                    bulk of the card's content.</p>
                                <a href="{{ route('user.doctor.specific',$specific_doctor_category_list->id) }}" class="btn btn-sm btn-primary">Show</a>
                                <a href="" class="btn btn-sm btn-success">Appointment</a>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>

        <!-- content End -->


        <!-- Footer Start -->
        <x-backend.partials.footer />
        <!-- Footer End -->

    </div>
    <!-- Content End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>



    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

</x-backend.layout.master>

patients-management-system-PMS/resources/views/backend/user/doctor_category/specific_doctor_category_list.blade.php
<x-backend.layout.master>

    <!-- Sidebar Start -->
    <x-backend.partials.sidebar />
    <!-- Sidebar End -->



    <!-- Content Start -->
    <div class="content">
        <!-- Navbar Start -->
        <x-backend.partials.navbar />
        <!-- Navbar End -->

        <!-- content Start -->

        <div class="container">
            <div class="row mx-4">
                <h3 class="text-center mt-3">Doctor Specialist</h3>
                @foreach ($specific_doctor_category_list as $specific_doctor_category_list)
                    <div class="col col-3">
                        <div class="card" style="width: 15rem; margin:auto;">
                            <img src="..." class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">
                                    {{ ucfirst($specific_doctor_category_list->first_name)}} 
                                    {{ ucfirst($specific_doctor_category_list->last_name)}} 
                                </h5>
                                <b class="card-title">{{ 
                                ucfirst($specific_doctor_category_list->doctorCategory->name)
                                 }} Specialist</b>

                                <p class="card-text">Some quick example text to build on the card title and make up
                                    the
                                    bulk of the card's content.</p>
                                <a href="{{ route('user.doctor.specific',$specific_doctor_category_list->id) }}" class="btn btn-sm btn-primary">Show</a>
                                <a href="" class="btn btn-sm btn-success">Appointment</a>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>

        <!-- content End -->


        <!-- Footer Start -->
        <x-backend.partials.footer />
        <!-- Footer End -->

    </div>
    <!-- Content End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>



    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

</x-backend.layout.master>