patients-management-system-PMS/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PdfController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\PrescriptionController;
use App\Http\Controllers\fontend\FontendController;
use App\Http\Controllers\backend\admin\AdminController;
use App\Http\Controllers\backend\admin\AllAdminController;
use App\Http\Controllers\backend\admin\AllPatientController;
use App\Http\Controllers\backend\user\UserProfileController;
use App\Http\Controllers\backend\admin\AdminProfileController;
use App\Http\Controllers\backend\user\UserDeshboardController;
use App\Http\Controllers\backend\user\DoctorCategoryController;
use App\Http\Controllers\backend\admin\AdminDeshboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('fontend.dashboard');
});

// Route::gat('/',[FontendController::class, 'dashboard']);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';



// Admin Controller
Route::prefix('admin')->name('admin.')->controller(AdminController::class)->group(function () {
    Route::get('/', 'adminLoginForm')->name('login.form');
    Route::post('/login', 'adminLogin')->name('login');
});

Route::middleware("admin")->group(function () {
    // Admin Deshboard Controller
    Route::prefix('admin')->name('admin.')->controller(AdminDeshboardController::class)->group(function () {
        Route::get('/register', 'adminRegstrationForm')->name('register.form');
        Route::post('/register/store', 'adminRegstrationStore')->name('register.store');
        Route::get('/deshboard', 'adminDeshboard')->name('deshboard');
        Route::get('/logout', 'adminLogout')->name('logout');
    });

    // Admin Profile Controller
    Route::prefix('admin')->name('admin.')->controller(AdminProfileController::class)->group(function () {
        Route::get('/profile', 'adminProfile')->name('profile');
        Route::post('/update/{id}', 'adminProfileUpdate')->name('profile.update');
    });


    //  All Admin Controller
    Route::prefix('admin')->name('admin.')->controller(AllAdminController::class)->group(function () {
        Route::get('/all/admins', 'allAdmins')->name('all');
        Route::get('/show/{id}', 'showAdmin')->name('show');
        Route::get('/edit/{id}', 'editAdmin')->name('edit');
        Route::put('/update/{id}', 'updateAdmin')->name('update');
        Route::delete('/delete/{id}', 'adminDelete')->name('destroy');
       
    });


    // All Patients Controller
    Route::prefix('patient')->name('patient.')->controller(AllPatientController::class)->group(function () {
        Route::get('/all', 'allPatients')->name('all');
        Route::get('/show/{id}', 'showPatient')->name('show');
        Route::get('/prescription/{id}', 'prescription')->name('prescription');
    });


    // User Profile Controller
    Route::prefix('user')->name('user.')->controller(UserProfileController::class)->group(function () {
        Route::get('/profile', 'UserProfile')->name('profile');
        Route::get('/profile.update', 'UserProfile')->name('profile.update');
        Route::get('/list', 'Userlist')->name('all.list');
    });
});


Route::middleware('auth')->group(function () {

    // User Deshboard Controller
    Route::prefix('user')->name('user.')->controller(UserDeshboardController::class)->group(function () {
        Route::get('/deshboard', 'UserDeshboard')->name('deshboard');
    });

    // Doctor Specialist Controller
    Route::prefix('doctor')->name('user.')->controller(DoctorCategoryController::class)->group(function () {
        Route::get('/list/{id}', 'doctorList')->name('specific.doctor.list');
        Route::get('/specific/show/{id}', 'doctorSpecific')->name('doctor.specific');
    });
});



//pascription controller

Route::prefix('admin')->name('admin.')->controller(PrescriptionController::class)->middleware('admin')->group(function () {
    Route::get('/prescription/list', 'prescription_list')->name('prescription.list');
    Route::get('/prescription/create/{id}', 'patients_prescription')->name('prescription.create');
    Route::post('/prescription/store', 'store')->name('prescription.store');
    Route::get('/prescription/show/{id}', 'show')->name('prescription.show');
});

// pdf 
    
Route::get('/prescription/Pdf', [PdfController::class, 'prescription_Pdf'])->name('prescription.pdf');
Route::get('/appointment/Pdf', [PdfController::class, 'appointment_Pdf'])->name('appointment.pdf');
    

//appointment controller

Route::prefix('appointment')->name('appointment.')->controller(AppointmentController::class)->group(function () {
    // Route::get('/', 'appointment_list')->name('list');
    Route::get('/', 'index')->name('list');
    Route::get('/create/{id}', 'appointment')->name('create');
    Route::get('/show/{id}', 'appointment_show')->name('show');
    Route::post('/store', 'store')->name('store');
    Route::get('/today', 'today_appointment')->name('today');
});

patients-management-system-PMS/app/Models/Prescription.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Prescription extends Model
{
    use HasFactory;
    protected $fillable = [
        'patient_name',
        'doctor_name',
        'doctor_category',
        'medicine',
        'age',
        'phone',
        'test',
        'disease',
        'gender',
        'next_appointment',
        'messages'
    ];
}

patients-management-system-PMS/app/Http/Controllers/PrescriptionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Appointment;
use Exception;

use App\Models\Prescription;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class PrescriptionController extends Controller
{



public function prescription_list(){

    if(request()->keyword){

        $prescription = Prescription::where('patient_name','like', '%' . request()->keyword. '%' )->get();
        return view('backend.admin.prescription.prescription_list', compact('prescription'));

    }else{
        $prescription= Prescription::all();

        return view('backend.admin.prescription.prescription_list',compact('prescription'));
    }

   
}

    public function patients_prescription($id){
        
        $patient =Appointment::find($id);
        
        return view('backend.admin.prescription.prescription',compact('patient'));
    }


    public function store(Request $request){


// dd($request->all());
        $request->validate([
            'patient_name'=>'required',
            'doctor_name'=>'required',
            'doctor_category'=>'required',
            'medicine'=>'required',
            'age'=>'required|numeric',
            'phone'=>'required|numeric',
            'test'=>'required',
            'disease'=>'required',
            'gender'=>'required',
            'next_appointment'=>'required',
            'message'=>'required',
        ]);

        
        try {
            
            
            $prescription = Prescription::create([
                'patient_name'=>$request->patient_name,
                'doctor_name'=>$request->doctor_name,
                'doctor_category'=>$request->doctor_category,
                'medicine'=>$request->medicine,
                'age'=>$request->age,
                'phone'=>$request->phone,
                'test'=>$request->test,
                'disease'=>$request->disease,
                'gender'=>$request->gender,
                'next_appointment'=>$request->next_appointment,
                'message'=>$request->message,
                
            ]);
            // dd($request->all());
            return redirect()->route('patient.all')->with('success',"Prescription Create Successfully");
        } catch (Exception $e) {
            return redirect()->back($e->getMessage());
        }
    }

    public function show($id){
        $prescription= Prescription::find($id);

        return view('backend.admin.prescription.show_prescription',['prescription'=>$prescription]);
    }
}

patients-management-system-PMS/resources/views/backend/admin/prescription/prescription.blade.php
<x-backend.layout.master>

    <!-- Sidebar Start -->
    <x-backend.partials.sidebar />
    <!-- Sidebar End -->



    <!-- Content Start -->
    <div class="content">
        <!-- Navbar Start -->
        <x-backend.partials.navbar />
        <!-- Navbar End -->

        <!-- content Start -->



        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @if (session('message'))
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{ session('message') }}!</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
        <div class="container mt-4">

            <form action="{{ route('admin.prescription.store') }}" method="POST"
                class="bg-light rounded-3 border border-5 border-primary">


                @csrf

                <div>
                    <h3 class="text-uppercase text-center text-white bg-primary p-2 ">pascription form</h3>
                </div>
                <div class="p-4 ">

                    <input type="hidden" id="ductor_name" placeholder="Physician-Name" name="doctor_name"
                        class="form-control" value="{{ auth('admin')->user()->first_name }}">

                    <input type="hidden" name="doctor_category" id=" doctor_category" class="form-control"
                        value="{{ auth('admin')->user()->doctor_category }}">



                    <div class="row mb-4">
                        <div class="col-8"></div>
                        <div class="col-1 text-end">
                            <label for="date" class="mt-1 text-uppercase fw-bolder">date:</label>
                        </div>

                        <div class="col-3">
                            <input type="date" name="date" id="date" class="form-control">
                        </div>

                    </div>


                    <div class="row mt-4">

                        <div class="col-2 text-end">
                            <label for="Patient Name" class=" mt-1 text-uppercase  fw-bolder">Patient-Name:</label>
                        </div>

                        <div class="col-4">
                            <input type="text" name="patient_name" id="Patient Name" class="form-control"
                                placeholder="Enter Patient Name" value={{ $patient->name }}>
                        </div>

                        <div class="col-3 text-end">

                            <label for="Phone Number" class="text-end mt-1 text-uppercase  fw-bolder">Patient
                                Phone-Number:</label>
                        </div>

                        <div class=" col-3">
                            <input type="number" name="phone" id="Phone Number" class="form-control"
                                placeholder="Enter Phone Number" value={{ $patient->phone }}>
                        </div>

                    </div>

                    <div class="row mt-4">

                        <div class="col-2 text-end mt-1">
                            <label for="sex" class=" text-uppercase  fw-bolder">Sex:</label>

                        </div>
                        <div class="col-3 mt-1">
                            <input type="radio" name="gender" id="sex">
                            <label for="">Male</label>
                            <input type="radio" name="gender" id="sex">
                            <label for="">Female</label>
                            <input type="radio" name="gender" id="sex">
                            <label for="">Others</label>

                        </div>

                        <div class="col-1 text-end">
                            <label for="age" class=" p-1 text-uppercase  fw-bolder">Age:</label>
                        </div>

                        <div class="col-2">
                            <input type="number" name="age" id="age" class="form-control" placeholder="Age">
                        </div>

                        <div class="col-2 text-end ">
                            <label for="date of birth" class="p-1 text-uppercase  fw-bolder">Date Of Birth:</label>
                        </div>

                        <div class="col-2">
                            <input type="date" name="date_of_birth" class="form-control">
                        </div>

                    </div>


                    <div class="row mt-4">

                        <div class="col-2 text-end">
                            <label for="disease" class="p-1 text-uppercase  fw-bolder">desiase:</label>
                        </div>

                        <div class="col-4">
                            <input type="text" name="disease" id="disease" class="form-control" placeholder="disease">
                        </div>

                        <div class="col-2 text-end">
                            <label for="room" class="p-1 text-uppercase  fw-bolder">Room No:</label>
                        </div>

                        <div class="col-4">
                            <select class="form-select" aria-label="multiple select example" name="room[]">
                                <option selected>401-BLock-D</option>
                                <option value="1">303-Block-f</option>
                                <option value="2">503-Block-e</option>
                            </select>
                        </div>
                    </div>


                    <div class="row mt-4">

                        <div class="col-2 text-end">
                            <label for="medicine" class="p-1 text-uppercase  fw-bolder">Medicine:</label>
                        </div>

                        <div class="col-4">
                            <select class="form-select" aria-label="multiple select example" name="medicine">
                                <option selected>Napa-10mg</option>
                                <option value="1">Finix-20mg</option>
                                <option value="2">Others</option>
                            </select>
                        </div>

                        <div class="col-3 text-end">
                            <label for="next_appointment"
                                class=" mt-1 text-uppercase  fw-bolder">next-appointment:</label>
                        </div>

                        <div class=" col-3">
                            <input type="date" name="next_appointment" id="next_appointmen" class="form-control">
                        </div>

                    </div>

                    <div class="row mt-4">

                        <div class="col-2"></div>
                        <div class="col-1 text-end mt-1">
                            <label for="test" class=" text-uppercase  fw-bolder">test:</label>
                        </div>
                        <div class="col-4">
                            <select class="form-select" aria-label="multiple select example" name="test">
                                <option selected>Napa-10mg</option>
                                <option value="1">Finix-20mg</option>
                                <option value="2">Others</option>
                            </select>
                        </div>
                        <div class="col-5"></div>
                    </div>


                    <div class="row mt-5">
                        <div class="col-3 text-end">
                            <label class="mt-3 text-uppercase  fw-bolder" for="message">Additional information:</label>
                        </div>


                        <div class="col-9">
                            <textarea class="form-control" name="message" id="message" rows="4"></textarea>
                        </div>

                    </div>

                    <div class="row mt-5">
                        <div class="col-5"></div>
                        <div class=" col-2  text-center">
                            <button type="submit"
                                class="text-uppercase  fw-bolder btn btn-outline-primary text-center p-2">Submit</button>
                        </div>
                        <div class="col-5"></div>

                    </div>


                </div>
            </form>
        </div>


        <!-- content End -->


        <!-- Footer Start -->
        <x-backend.partials.footer />
        <!-- Footer End -->

    </div>
    <!-- Content End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>



    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

</x-backend.layout.master>

patients-management-system-PMS/resources/views/backend/admin/prescription/prescription_list.blade.php
a<x-backend.layout.master>

    <!-- Sidebar Start -->
    <x-backend.partials.sidebar />
    <!-- Sidebar End -->



    <!-- Content Start -->
    <div class="content">
        <!-- Navbar Start -->
        <x-backend.partials.navbar />
        <!-- Navbar End -->

        <!-- content Start -->
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @if (session('message'))
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{ session('message') }}!</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
        @if (session('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('success') }}!</strong> <button type="button" class="btn-close"
                    data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif


        <div class="container mt-5">
            <div class="text-end ">
                <a href="{{ route('prescription.pdf') }}" class="btn btn-sm btn-primary mb-3">PDF</a>
            </div>

            <div class="container">

                <form action="" method="GET" class="d-flex mb-5">

                    <input type="text" name="keyword" placeholder="Search Here " class="form-control" />

                    <button class="btn btn-sm btn-primary">Search </button>

                </form>

            </div>


            <table class="table table table-striped  table table-bordered border-warning">
                <thead class="table-dark">
                    <tr class="text-center">
                        <th scope="col">Ser No</th>
                        <th scope="col"> Patient_Name</th>
                        <th scope="col">Doctor_Name</th>
                        <th scope="col">Doctor_Category</th>
                        <th scope="col">Medicine</th>
                        <th scope="col" class="text-center">Action</th>
                        {{-- <th scope="col">Age</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Test</th> --}}
                        {{-- <th scope="col">Disease</th> --}}
                        {{-- <th scope="col">Gender</th>
                        <th scope="col">Next_appointment</th>
                        <th scope="col">Message</th> --}}
                    </tr>
                </thead>
                <tbody>



                    @foreach ($prescription as $key => $prescription)
                        <tr class="text-center">
                            <td scope="row">{{ $key + 1 }}</td>
                            <td>{{ $prescription->patient_name }}</td>
                            <td>{{ $prescription->doctor_name }}</td>
                            <td>{{ $prescription->doctor_category }}</td>
                            <td>{{ $prescription->medicine }}</td>
                            <td class="text-center">

                                <a href="{{ route('admin.prescription.show', $prescription->id) }}"
                                    class="btn btn-sm btn-warning">SHOW</a>
                                <a href="#" class="btn btn-sm btn-danger">DELETE</a>
                            </td>

                            {{-- <td>{{ $prescription->age }}</td>
                            <td>{{ $prescription->phone }}</td>
                            <td>{{ $prescription->test }}</td> --}}
                            {{-- <td>{{ $prescription->disease }}</td> --}}
                            {{-- <td>{{ $prescription->gender }}</td>
                            <td>{{ $prescription->next_appointment }}</td>
                            <td>{{ $prescription->message }}</td> --}}

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <!-- content End -->


        <!-- Footer Start -->
        <x-backend.partials.footer />
        <!-- Footer End -->

    </div>
    <!-- Content End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>



    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

</x-backend.layout.master>

patients-management-system-PMS/resources/views/backend/admin/prescription/prescription_pdf.blade.php
    <table>
        <thead class="table-dark">
            <tr class="text-center">
                <th scope="col">Ser No</th>
                <th scope="col"> Patient_Name</th>
                <th scope="col">Doctor_Name</th>
                <th scope="col">Doctor_Category</th>
                <th scope="col">Medicine</th>
                <th scope="col">Age</th>
                <th scope="col">Phone</th>
                <th scope="col">Test</th> 
                <th scope="col">Disease</th>
                <th scope="col">Gender</th>
                <th scope="col">Next_appointment</th>
                <th scope="col">Message</th>
                
            </tr>
        </thead>
        <tbody>

           

            @foreach ($prescription as $key => $prescription)
                <tr class="text-center">
                    <td scope="row">{{ $key + 1 }}</td>
                    <td>{{ $prescription->patient_name }}</td>
                    <td>{{ $prescription->doctor_name }}</td>
                    <td>{{ $prescription->doctor_category }}</td>
                    <td>{{ $prescription->medicine }}</td>
                    <td>{{ $prescription->age }}</td>
                    <td>{{ $prescription->phone }}</td>
                    <td>{{ $prescription->test }}</td>
                    <td>{{ $prescription->disease }}</td>
                    <td>{{ $prescription->gender }}</td>
                    <td>{{ $prescription->next_appointment }}</td>
                    <td>{{ $prescription->message }}</td>
                    
                </tr>
            @endforeach
        </tbody>
    </table>

    <style>

        table, th , td {
            padding: 20px;
            border: 1px solid black;
            border-collapse: collapse;   
        }
    
        table{
            width:100%;
        }
    
    
    </style>

patients-management-system-PMS/resources/views/backend/admin/prescription/show_prescription.blade.php
<x-backend.layout.master>

    <!-- Sidebar Start -->
    <x-backend.partials.sidebar />
    <!-- Sidebar End -->



    <!-- Content Start -->
    <div class="content">
        <!-- Navbar Start -->
        <x-backend.partials.navbar />
        <!-- Navbar End -->

        <!-- content Start -->

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @if (session('message'))
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{ session('message') }}!</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
        <div class="container mt-4">
            <div class=" card card-body">
                <p>Patient Name: {{ $prescription->patient_name }} </p>
                <p>Doctor Name: {{ $prescription->doctor_name }} </p>
                <p>Doctor Category: {{ $prescription->doctor_category }} </p>
                <p>Medicine: {{ $prescription->medicine }} </p>
                <p>Age: {{ $prescription->age }} </p>
                <p>Phone Number: {{ $prescription->phone }} </p>
                <p>Test: {{ $prescription->test }} </p>
                <p>Disease: {{ $prescription->disease }} </p>
                <p>Gender: {{ $prescription->gender }} </p>
                <p>Next Appointment: {{ $prescription->next_appointment }} </p>
                <p>Message: {{ $prescription->message }} </p>
            </div>
        </div>


        <!-- content End -->


        <!-- Footer Start -->
        <x-backend.partials.footer />
        <!-- Footer End -->

    </div>
    <!-- Content End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>




    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


</x-backend.layout.master>