patients-management-system-PMS/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PdfController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\PrescriptionController;
use App\Http\Controllers\fontend\FontendController;
use App\Http\Controllers\backend\admin\AdminController;
use App\Http\Controllers\backend\admin\AllAdminController;
use App\Http\Controllers\backend\admin\AllPatientController;
use App\Http\Controllers\backend\user\UserProfileController;
use App\Http\Controllers\backend\admin\AdminProfileController;
use App\Http\Controllers\backend\user\UserDeshboardController;
use App\Http\Controllers\backend\user\DoctorCategoryController;
use App\Http\Controllers\backend\admin\AdminDeshboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('fontend.dashboard');
});

// Route::gat('/',[FontendController::class, 'dashboard']);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';



// Admin Controller
Route::prefix('admin')->name('admin.')->controller(AdminController::class)->group(function () {
    Route::get('/', 'adminLoginForm')->name('login.form');
    Route::post('/login', 'adminLogin')->name('login');
});

Route::middleware("admin")->group(function () {
    // Admin Deshboard Controller
    Route::prefix('admin')->name('admin.')->controller(AdminDeshboardController::class)->group(function () {
        Route::get('/register', 'adminRegstrationForm')->name('register.form');
        Route::post('/register/store', 'adminRegstrationStore')->name('register.store');
        Route::get('/deshboard', 'adminDeshboard')->name('deshboard');
        Route::get('/logout', 'adminLogout')->name('logout');
    });

    // Admin Profile Controller
    Route::prefix('admin')->name('admin.')->controller(AdminProfileController::class)->group(function () {
        Route::get('/profile', 'adminProfile')->name('profile');
        Route::post('/update/{id}', 'adminProfileUpdate')->name('profile.update');
    });


    //  All Admin Controller
    Route::prefix('admin')->name('admin.')->controller(AllAdminController::class)->group(function () {
        Route::get('/all/admins', 'allAdmins')->name('all');
        Route::get('/show/{id}', 'showAdmin')->name('show');
        Route::get('/edit/{id}', 'editAdmin')->name('edit');
        Route::put('/update/{id}', 'updateAdmin')->name('update');
        Route::delete('/delete/{id}', 'adminDelete')->name('destroy');
       
    });


    // All Patients Controller
    Route::prefix('patient')->name('patient.')->controller(AllPatientController::class)->group(function () {
        Route::get('/all', 'allPatients')->name('all');
        Route::get('/show/{id}', 'showPatient')->name('show');
        Route::get('/prescription/{id}', 'prescription')->name('prescription');
    });


    // User Profile Controller
    Route::prefix('user')->name('user.')->controller(UserProfileController::class)->group(function () {
        Route::get('/profile', 'UserProfile')->name('profile');
        Route::get('/profile.update', 'UserProfile')->name('profile.update');
        Route::get('/list', 'Userlist')->name('all.list');
    });
});


Route::middleware('auth')->group(function () {

    // User Deshboard Controller
    Route::prefix('user')->name('user.')->controller(UserDeshboardController::class)->group(function () {
        Route::get('/deshboard', 'UserDeshboard')->name('deshboard');
    });

    // Doctor Specialist Controller
    Route::prefix('doctor')->name('user.')->controller(DoctorCategoryController::class)->group(function () {
        Route::get('/list/{id}', 'doctorList')->name('specific.doctor.list');
        Route::get('/specific/show/{id}', 'doctorSpecific')->name('doctor.specific');
    });
});



//pascription controller

Route::prefix('admin')->name('admin.')->controller(PrescriptionController::class)->middleware('admin')->group(function () {
    Route::get('/prescription/list', 'prescription_list')->name('prescription.list');
    Route::get('/prescription/create/{id}', 'patients_prescription')->name('prescription.create');
    Route::post('/prescription/store', 'store')->name('prescription.store');
    Route::get('/prescription/show/{id}', 'show')->name('prescription.show');
});

// pdf 
    
Route::get('/prescription/Pdf', [PdfController::class, 'prescription_Pdf'])->name('prescription.pdf');
Route::get('/appointment/Pdf', [PdfController::class, 'appointment_Pdf'])->name('appointment.pdf');
    

//appointment controller

Route::prefix('appointment')->name('appointment.')->controller(AppointmentController::class)->group(function () {
    // Route::get('/', 'appointment_list')->name('list');
    Route::get('/', 'index')->name('list');
    Route::get('/create/{id}', 'appointment')->name('create');
    Route::get('/show/{id}', 'appointment_show')->name('show');
    Route::post('/store', 'store')->name('store');
    Route::get('/today', 'today_appointment')->name('today');
});

patients-management-system-PMS/app/Models/Appointment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Appointment extends Model
{
    use HasFactory;
    protected $guarded=[];
}

patients-management-system-PMS/app/Http/Controllers/AppointmentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Admin;
use Exception;
use App\Models\Appointment;
use Illuminate\Http\Request;
use App\Models\DoctorCategory;
use Carbon\Carbon;

class AppointmentController extends Controller
{

    public function index()
    {
        $appointments = Appointment::all();

        return view('appointment.appointment_list', compact('appointments'));
    }

    public function appointment_show($id)
    {
        $appointment = Appointment::find($id);
        return view('appointment.show_appointment', compact('appointment'));
    }

    public function appointment($id)
    {
        $doctor = Admin::findOrFail($id);
        return view('appointment.appointment_form', compact('doctor'));
    }

    public function store(Request $request)
    {

        $request->validate([
            'patient_name' => 'required',
            'doctor_name' => 'required',
            'doctor_category' => 'required',
            'age' => 'required|numeric',
            'phone' => 'required|numeric',
            'gender' => 'required',
            'appointment_date' => 'required',
            'address' => 'required',
            'description' => 'required',

        ]);




        try {


            $appointment = Appointment::create([

                'doctor_id' => $request->doctor_id,
                'patient_name' => $request->patient_name,
                'doctor_name' => $request->doctor_name,
                'doctor_category' => $request->doctor_category,
                'age' => $request->age,
                'phone' => $request->phone,
                'gender' => $request->gender,
                'appointment_date' => $request->appointment_date,
                'address' => $request->address,
                'description' => $request->description,

            ]);
            // dd($request->all());
            return redirect()->route('user.deshboard')->with('success', "Appointment Successfully");
        } catch (Exception $e) {
            dd($e->getMessage());
            return redirect()->back($e->getMessage());
        }
    }


    public function today_appointment()
    {

        $appointment_today = Appointment::where('doctor_id', auth('admin')->user()->id)->whereDate('created_at', Carbon::today())->get();

        return view('appointment.today_appointment', compact('appointment_today'));
    }


    public function show($id)
    {
        $prescription = Appointment::find($id);

        return view('backend.admin.prescription.show_prescription', ['prescription' => $prescription]);
    }
}

patients-management-system-PMS/resources/views/appointment/appointment_form.blade.php
<x-backend.layout.master>

    <!-- Sidebar Start -->
    <x-backend.partials.sidebar />
    <!-- Sidebar End -->



    <!-- Content Start -->
    <div class="content">
        <!-- Navbar Start -->
        <x-backend.partials.navbar />
        <!-- Navbar End -->

        <!-- content Start -->

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @if (session('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('success') }}!</strong> <button type="button" class="btn-close"
                    data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif

        <div class="container mt-4">

            <section class=" appoinment p-4 rounded-1" style="background-color: #71b4b4">
                <div class="container">
                    <div class="row ">

                        <div class="col-lg-3 ">

                        </div>

                        <div class="col-lg-6 col-md-10 ">
                            <div class=" mt-5 mt-lg-0">
                                <h2 class="mb-2 text-center ">Book appoinment</h2>
                                <p class="mb-4 text-white">Mollitia dicta commodi est recusandae iste, natus eum
                                    asperiores corrupti qui velit . Iste dolorum atque similique praesentium soluta.
                                </p>

                                <form class="" method="post" action="{{ route('appointment.store') }}">
                                    @csrf

                                    <input type="hidden" name="doctor_id" id="" value="{{ $doctor->id }}">

                                    <input type="hidden" name="doctor_name" value="{{ $doctor->first_name }} {{ $doctor->last_name }}" >

                                    <input type="hidden" name="doctor_category" value="{{ $doctor->doctor_category }}">

                                    <div class="row">
                                       

                                        
                                        <div class="col-lg-6 mt-3 ">
                                            <div class="text-start">
                                                <h6 class="title-color text-underline"><u>Patient Name:</u> </h6>
                                            </div>
                                            <div class="form-group">
                                                <input type="text" name="patient_name" id="patient_name"
                                                    class="form-control" placeholder="Patient Name">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 mt-3 ">
                                            <div class="text-start">
                                                <h6 class="title-color text-underline"><u>Phone Number:</u> </h6>
                                            </div>
                                            <div class="form-group">
                                                <input type="number" name="phone" id="phone" class="form-control"
                                                    placeholder="Phone Number">
                                            </div>
                                        </div>

                                        <div class="col-lg-6 mt-3">
                                            <div class="text-start">
                                                <h6 class="title-color text-underline"><u>Appointment Date:</u> </h6>
                                            </div>
                                            <div class="form-group">
                                                <input name="appointment_date" id="date" type="date"
                                                    class="form-control">
                                            </div>
                                        </div>

                                        <div class="col-lg-6 mt-3">
                                            <div class="form-group">
                                                <div class="text-start">
                                                    <h6 class="title-color text-underline">Age:</h6>
                                                </div>
                                                <input name="age" id="time" type="number" class="form-control"
                                                    placeholder="Age">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 mt-3">
                                            <div class="text-start">
                                                <h6 class="title-color text-underline"><u>Gender:</u> </h6>
                                            </div>
                                            <div class="text-start">
                                                <input name="gender" id="name" type="radio" class=""
                                                    placeholder="Full Name">
                                                <label for="">
                                                    <h6>Male</h6>
                                                </label>
                                                <input name="gender" id="name" type="radio" class=""
                                                    placeholder="Full Name">
                                                <label for="">
                                                    <h6>Female</h6>
                                                </label>
                                                <input name="gender" id="name" type="radio" class=""
                                                    placeholder="Full Name">
                                                <label for="">
                                                    <h6>Others</h6>
                                                </label>
                                            </div>
                                        </div>

                                    </div>

                                    <div class="form-group mb-4">
                                        <div class="text-start">
                                            <h6 class="title-color text-underline"><u>Patient Address:</u> </h6>
                                        </div>
                                        <textarea name="address" id="address" class="form-control" rows="3"
                                            placeholder="House No/Rood No/Area/City-City-code"></textarea>
                                    </div>

                                    <div class="form-group-2 mb-4">
                                        <div class="text-start">
                                            <h6 class="title-color text-underline"><u>About Problem:</u> </h6>
                                        </div>
                                        <textarea name="description" id="description" class="form-control" rows="6" placeholder="Your Message"></textarea>
                                    </div>

                                    <button type="submit" class="btn btn-main btn-round-full btn-primary" >Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

        </div>


        <!-- content End -->


        <!-- Footer Start -->
        <x-backend.partials.footer />
        <!-- Footer End -->

    </div>
    <!-- Content End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>




    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


</x-backend.layout.master>

patients-management-system-PMS/resources/views/appointment/appointment_list.blade.php
<x-backend.layout.master>

    <!-- Sidebar Start -->
    <x-backend.partials.sidebar />
    <!-- Sidebar End -->



    <!-- Content Start -->
    <div class="content">
        <!-- Navbar Start -->
        <x-backend.partials.navbar />
        <!-- Navbar End -->

        <!-- content Start -->
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @if (session('message'))
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{ session('message') }}!</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
        @if (session('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('success') }}!</strong> <button type="button" class="btn-close"
                    data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif


        <div class="container mt-5">

            <div class="text-end ">
                <a href="{{ route('appointment.pdf') }}" class="btn btn-sm btn-primary mb-3">PDF</a>
            </div>


            <table class="table table table-striped  table table-bordered border-warning">
                <thead class="table-dark">
                    <tr class="text-center">
                        <th scope="col">Ser No</th>
                        <th scope="col"> Patient_Name</th>
                        <th scope="col">Doctor_Name</th>
                        <th scope="col">Doctor_Category</th>
                        <th scope="col">Appointment Date</th>
                        <th scope="col" class="text-center">Action</th>
                        {{-- <th scope="col">Age</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Test</th> --}}
                        {{-- <th scope="col">Disease</th> --}}
                        {{-- <th scope="col">Gender</th>
                        <th scope="col">Next_appointment</th>
                        <th scope="col">Message</th>
                         --}}
                    </tr>
                </thead>
                <tbody>

                   

                    @foreach ($appointments as $key => $appointment)
                        <tr class="text-center">
                            <td scope="row">{{ $key + 1 }}</td>
                            <td>{{ $appointment->patient_name }}</td>
                            <td>{{ $appointment->doctor_name }}</td>
                            <td>{{ $appointment->doctor_category }}</td>
                            <td>{{ $appointment->appointment_date }}</td>
                            <td class="text-center">

                                <a href="{{ route('appointment.show',$appointment->id) }}" class="btn btn-sm btn-warning">SHOW</a>
                                
                            </td>

                            {{-- <td>{{ $appointment->age }}</td>
                            <td>{{ $appointment->phone }}</td>
                            <td>{{ $appointment->test }}</td> --}}
                            {{-- <td>{{ $appointment->disease }}</td> --}}
                            {{-- <td>{{ $appointment->gender }}</td>
                            <td>{{ $appointment->next_appointment }}</td>
                            <td>{{ $appointment->message }}</td> --}}
                            
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <!-- content End -->


        <!-- Footer Start -->
        <x-backend.partials.footer />
        <!-- Footer End -->

    </div>
    <!-- Content End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>



    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

</x-backend.layout.master>

patients-management-system-PMS/resources/views/appointment/appointment_pdf.blade.php
<table class="table table table-striped  table table-bordered border-warning">
    <thead class="table-dark">
        <tr class="text-center">
            <th scope="col">Ser No</th>
            <th scope="col"> Patient_Name</th>
            <th scope="col">Doctor_Name</th>
            <th scope="col">Doctor_Category</th>
            <th scope="col">Appointment Date</th>
           
        
    </thead>
    <tbody>

       

        @foreach ($appointment as $key => $appointment)
            <tr class="text-center">
                <td scope="row">{{ $key + 1 }}</td>
                <td>{{ $appointment->patient_name }}</td>
                <td>{{ $appointment->doctor_name }}</td>
                <td>{{ $appointment->doctor_category }}</td>
                <td>{{ $appointment->appointment_date }}</td>
               

                
            </tr>
        @endforeach
    </tbody>
</table>


<style>

    table, th , td {
        padding: 20px;
        border: 1px solid black;
        border-collapse: collapse;   
    }

    table{
        width:100%;
    }


</style>

patients-management-system-PMS/resources/views/appointment/show_appointment.blade.php
<x-backend.layout.master>

    <!-- Sidebar Start -->
    <x-backend.partials.sidebar />
    <!-- Sidebar End -->



    <!-- Content Start -->
    <div class="content">
        <!-- Navbar Start -->
        <x-backend.partials.navbar />
        <!-- Navbar End -->

        <!-- content Start -->
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>

            </div>
        @endif

        @if (session('message'))
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{ session('message') }}!</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
        @if (session('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('success') }}!</strong> <button type="button" class="btn-close"
                    data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif


        <div class="container mt-5">

            <div class="mb-3"><a href="{{ route('appointment.list') }}" class="btn btn-sm btn-primary">back</a></div>
            <div class="card card-body">

                <p>Patient Name: {{ $appointment->patient_name }}</p>
                <p>Doctor Name: {{ $appointment->doctor_name }}</p>
                <p>Doctor Category: {{ $appointment->doctor_category }}</p>
                <p>Phone: {{ $appointment->phone }}</p>
                <p>Gender: {{ $appointment->gender }}</p>
                <p>Age: {{ $appointment->age }}</p>
                <p>Description: {{ $appointment->description }}</p>
                <p>Appointment_Date: {{ $appointment->appointment_date }}</p>
                <p>Address: {{ $appointment->address }}</p>
                
                

            </div>



        </div>



        <!-- content End -->


        <!-- Footer Start -->
        <x-backend.partials.footer />
        <!-- Footer End -->

    </div>
    <!-- Content End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>




    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


</x-backend.layout.master>

patients-management-system-PMS/resources/views/appointment/today_appointment.blade.php
{{-- @foreach ($appointment_today as $value)
{{ $value->patient_name }}
@endforeach --}}


<x-backend.layout.master>

    <!-- Sidebar Start -->
    <x-backend.partials.sidebar />
    <!-- Sidebar End -->



    <!-- Content Start -->
    <div class="content">
        <!-- Navbar Start -->
        <x-backend.partials.navbar />
        <!-- Navbar End -->

        <!-- content Start -->
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @if (session('message'))
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{ session('message') }}!</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
        @if (session('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('success') }}!</strong> <button type="button" class="btn-close"
                    data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif


        <div class="container mt-5">


            <table class="table table table-striped  table table-bordered border-warning">
                <thead class="table-dark">
                    <tr class="text-center">
                        <th scope="col">Ser No</th>
                        <th scope="col"> Patient_Name</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Gender</th>
                        <th scope="col">Age</th>
                        <th scope="col" class="text-center">Action</th>
                        {{-- <th scope="col">Age</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Test</th> --}}
                        {{-- <th scope="col">Disease</th> --}}
                        {{-- <th scope="col">Gender</th>
                        <th scope="col">Next_appointment</th>
                        <th scope="col">Message</th>
                         --}}
                    </tr>
                </thead>
                <tbody>

                   

                    @foreach ($appointment_today as $key => $value)
                        <tr class="text-center">
                            <td scope="row">{{ $key + 1 }}</td>
                            <td>{{ $value->patient_name }}</td>
                            <td>{{ $value->phone }}</td>
                            <td>{{ $value->gender }}</td>
                            <td>{{ $value->age }}</td>
                            <td class="text-center">

                                <a href="#" class="btn btn-sm btn-warning">SHOW</a>
                                <a class="btn btn-primary" href="{{ route('admin.prescription.create', $value->id)}}">Prescription</a>
                              
                               
                            </td>

                            {{-- <td>{{ $appointment->age }}</td>
                            <td>{{ $appointment->phone }}</td>
                            <td>{{ $appointment->test }}</td> --}}
                            {{-- <td>{{ $appointment->disease }}</td> --}}
                            {{-- <td>{{ $appointment->gender }}</td>
                            <td>{{ $appointment->next_appointment }}</td>
                            <td>{{ $appointment->message }}</td> --}}
                            
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <!-- content End -->


        <!-- Footer Start -->
        <x-backend.partials.footer />
        <!-- Footer End -->

    </div>
    <!-- Content End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>



    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

</x-backend.layout.master>